$schema = "./node_modules/wrangler/config-schema.json"
name = "crontab-clock"
main = "worker/index.js"
compatibility_date = "2026-02-10"
workers_dev = true

[assets]
directory = "./_site"
binding = "ASSETS"
run_worker_first = true
